// THIS IS AUTOGENERATED FILE. DO NOT MODIFY IT. CONTENT WILL BE REPLACED ON NEW NPM INSTALL
const { pathsToModuleNameMapper } = require('ts-jest');

const { compilerOptions } = require('./tsconfig.json');

module.exports = {
  rootDir: './',
  clearMocks: true,
  collectCoverage: true,
  coverageProvider: 'v8',
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  coveragePathIgnorePatterns: ['node_modules/', '(tests/.*.mock).(jsx?|tsx?)$'],
  testMatch: ['<rootDir>/**/__tests__/**/*.(spec|test).ts'],
  preset: 'ts-jest',
  moduleDirectories: ['node_modules'],
  testPathIgnorePatterns: ['/node_modules/', '<rootDir>/dist', '<rootDir>/.build', '<rootDir>/.serverless'],
  transformIgnorePatterns: ['node_modules/(?!(@calo|lodash-es|calo-backend-types)).+\\.js$']
};
