Resources:
    MyTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: workshop-qasim-myTable-${sls:stage}
            KeySchema:
                -
                    AttributeName: pk
                    KeyType: HASH
                -
                    AttributeName: sk
                    KeyType: RANGE
            AttributeDefinitions:
                 -
                    AttributeType: S
                    AttributeName: pk
                 -
                    AttributeType: S
                    AttributeName: sk
            BillingMode: PAY_PER_REQUEST
            

