Resources:
    EmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: email-queue-${sls:stage}

    EmailQueueSNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        RawMessageDelivery: true
        TopicArn:
          Ref: SubscriptionCreatedTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt:
            - EmailQueue
            - Arn

    EmailSQSPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: EmailQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action: SQS:SendMessage
              Effect: Allow
              Principal:
                Service: "sns.amazonaws.com"
              Resource:
                - Fn::GetAtt:
                    - EmailQueue
                    - Arn
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: SubscriptionCreatedTopic

    SMSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sms-queue-${sls:stage}

    SMSQueueSNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        RawMessageDelivery: true
        TopicArn:
          Ref: SubscriptionCreatedTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt:
            - SMSQueue
            - Arn

    SMSSQSPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: SMSQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action: SQS:SendMessage
              Effect: Allow
              Principal:
                Service: "sns.amazonaws.com"
              Resource:
                - Fn::GetAtt:
                    - SMSQueue
                    - Arn
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: SubscriptionCreatedTopic